### ISSUE TITLE
Update to the latest React (18) dependancy

### ISSUE THREAD

**Issue by ray-marr-ho** [daniel-ac-martin/NotGovUK#1026]
Are there any plans to update to React 18?
I am working on some projects using React 18 where we're unable to use the library without `--legacy-peer-deps` due to React version

**Comment by daniel-ac-martin** [comment]
@ray-marr-ho: Yes, this is planned. I _think_ all it needs are updates to the types to make `children` explicit.

PRs are welcome for that!

**Comment by daniel-ac-martin** [comment]
@ray-marr-ho: Assuming that you are only using the components, as of v0.10.0, they _should_ now work with React v18.
I've not been able to upgrade this repo to React v18 yet though (I ran into hydration issues), so please let me know if you run into any problems.

**Comment by ray-marr-ho** [comment]
> @ray-marr-ho: Assuming that you are only using the components, as of v0.10.0, they _should_ now work with React v18. I've not been able to upgrade this repo to React v18 yet though (I ran into hydration issues), so please let me know if you run into any problems.

Thanks Daniel, it's still complaining on import. Which I think is because of the peerDeps in this file:
`https://github.com/daniel-ac-martin/NotGovUK/blob/master/packages/components/package.json`

**Comment by daniel-ac-martin** [comment]
@ray-marr-ho: Sorry. Could you try v0.12.1?
(Check the breaking changes listed against v0.12 and v0.11, although if you are only using the components, they may not affect you. - https://github.com/daniel-ac-martin/NotGovUK/releases )
