### ISSUE TITLE
Prototype generator - error with an unexpected character 

### ISSUE THREAD

**Issue by karypun** [daniel-ac-martin/NotGovUK#113]
Message received when generating a new prototype:

<img width="623" alt="Screenshot 2020-08-26 at 17 33 24" src="https://user-images.githubusercontent.com/13965310/91331327-8b99b700-e7c2-11ea-801c-38409f70562b.png">

**Comment by RobinKnipe** [comment]
Is that because you were trying to use emojis somewhere odd?

**Comment by daniel-ac-martin** [comment]
It's webpack failing to parse a file. I'm not even sure what a `.node` file is.

I'm guessing it's doing something odd on OSX.

**Comment by daniel-ac-martin** [comment]
> The FSEvents API in MacOS allows applications to register for notifications of changes to a given directory tree. It is a very fast and lightweight alternative to kqueue.
I guess so...

**Comment by daniel-ac-martin** [comment]
Sounds like we could fix this by upgrading webpack: https://github.com/webpack/webpack/issues/10783#issuecomment-619542931

I think my most recent attempt at that failed though...

**Comment by daniel-ac-martin** [comment]
Webpack v5 PR: https://github.com/daniel-ac-martin/NotGovUK/pull/95

**Comment by daniel-ac-martin** [comment]
This is fixed and will be in the next release.

We may still have a problem in #118 though.
