### ISSUE TITLE
Property 'hot' does not exist on type 'NodeModule' error & fix

### ISSUE THREAD

**Issue by sulthan-ahmed** [daniel-ac-martin/NotGovUK#134]
Not sure if you can do anything about this once I've installed the framework and I do prototype -> `npm install` I get the following error
`Property 'hot' does not exist on type 'NodeModule'`
I fixed it by doing npm i -D @types/webpack-env
https://stackoverflow.com/questions/40568176/webpack-typescript-module-hot-does-not-exist/44146354

perhaps you could add this as a dev dependency 
or you could add a common error & fix section

**Comment by daniel-ac-martin** [comment]
Sorry for the late response. I have a fix for this. I'll post here again when it's published.

**Comment by daniel-ac-martin** [comment]
Basically it's because we need to reference `webpack-env` in the `tsconfig.json`.

**Comment by sulthan-ahmed** [comment]
Ok thanks for explaining

**Comment by daniel-ac-martin** [comment]
Fixed in v0.1.27. (Just re-generate the prototype.)
