### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by JCWBiles** [daniel-ac-martin/NotGovUK#198]
Hi guys, there are a number of links that aren't working for me.
I'll do my best to list them here:

- README.md - "our documentation site" - https://not-govuk.netlify.app/
- README.md - all the links in "Contributing" section
- About NotGovUK - "NotGovUK" - https://not-govuk.netlify.app/
- About NotGovUK - "Design decisions" - https://github.com/daniel-ac-martin/NotGovUK/blob/master/docs/design-decisions
- About NotGovUK - "Getting started" - https://github.com/daniel-ac-martin/NotGovUK/blob/master/docs/get-started
- Getting Started - "Working on your project" - https://github.com/daniel-ac-martin/NotGovUK/blob/master/docs/working-on-your-project

Additional issue - on the "Getting Started" page in step 3, Answer the interactive prompts - the code snippet you provided `pnpm install` is different to what is the link you provided "install pnpm" - https://pnpm.js.org/en/installation. The site has a code snippet of `npm install -g pnpm`

**Comment by daniel-ac-martin** [comment]
Hi @JCWBiles.

Sorry for the late reply. I had problems with the hosting for the website so it was down for a while. It's back up now though. The broken links that you encountered should work on the website although they are broken when browsing through GitHub. (I need to think about how best to fix that.) - https://not-govuk.netlify.app/

The pnpm installation command is listed on the pnpm website as the second installation option.

Thanks for the feedback! Please get in touch if you have any more problems.
