### ISSUE TITLE
Don't force "govuk-link" class

### ISSUE THREAD

**Issue by RobinKnipe** [daniel-ac-martin/NotGovUK#223]
https://github.com/daniel-ac-martin/NotGovUK/blob/62eaefee491670498bbdfffd5994451e95cfd661/components/link/assets/Link.scss#L4-L6

This include forces `govuk-link` styles on to every anchor! This means a lot of fluff to override if you want to change the styling.

Instead, links should be more neutral, and the desired styles explicitly requested.

**Comment by daniel-ac-martin** [comment]
It's not just about devs creating components though.

If you were a designer (or even a dev) and you were building a page how would you expect to add a link to the page? How would you expect the link to look?

I would expect to be able to add a link with:
```html
<a href="http://bbc.co.uk">BBC</a>
```

And I would expect it to be styled according to the rest of the website.

So I think it's right to override the base styles. (And so you would need to deal with that when building components.)

There is a question of where the right place to do this is though.

**Comment by RobinKnipe** [comment]
Ok, I can see the merit in having base styles for the standard case you describe.
Perhaps something that would help is a pre-styled "button" (or set of buttons) for common use cases. Maybe even a component that accepts easier styling through attributes, e.g.
```jsx
<Button text-colour="black" background-colour="yellow">Bumble-bee button</Button>
<Button theme="hmpo">Big purple button</Button>
```
