### ISSUE TITLE
aria expanded for radios with conditonal

### ISSUE THREAD

**Issue by gavinthomas-valtech** [daniel-ac-martin/NotGovUK#654]
Adding aria expanded to conditionals in radios improves support for screenreaders knowing that the panel/info has been exposed

related issues:

https://github.com/w3c/aria/issues/1404

https://github.com/alphagov/govuk-frontend/issues/979

> In March 2021, we spoke to a Lead Auditor at the Digital Accessibility Centre who works alongside screen reader testers and users with disabilities. They audit a lot of government services, especially HMRC services. As such, they're pretty familiar with the current approach to conditional reveals.

>They mentioned that they’d known about the invalid use of aria-expanded for a while, but not really flagged it as it’s normally read by screen readers (at least the versions of JAWS and NVDA they test with, would have to check Voiceover).

Happy to try and create a PR for this

**Comment by gavinthomas-valtech** [comment]
gov uk uses aria expanded on conditionals
https://design-system.service.gov.uk/components/radios/

**Comment by robpataki** [comment]
Good shout @gavinthomas-valtech. There is an article about this on the GOVUK Blog: https://accessibility.blog.gov.uk/2021/09/21/an-update-on-the-accessibility-of-conditionally-revealed-questions/

**Comment by daniel-ac-martin** [comment]
Hi @gavinthomas-valtech.
Thanks for reminding me about this. We don't yet properly support conditional reveals on radios. If memory serves, there's some complication with implementing this in React while supporting isomorphic rendering. I'll have to have a look at how I did it for checkboxes. (Although handing the state is simpler there.)

@robpataki: Thanks for pointing out the discussion on this. Will be interesting to see if `aria-expanded` is kept in place.

At the very least, we should add `aria-expanded` to the Checkboxes.

**Comment by daniel-ac-martin** [comment]
@gavinthomas-valtech: This should be fixed in the next version (v0.6.0).
