### ISSUE TITLE
Hint always referenced, error message never

### ISSUE THREAD

**Issue by robpataki** [daniel-ac-martin/NotGovUK#656]
## Issue description

There are 2 related issues in the following Form components: TextInput, TextArea and FormGroup (which automatically fixes DateInput, Radios and Checkboxes). These components seem to have 2 accessibility and validation issues which are:

1. Hint is always referenced by ID in `aria-describedby` in these components, even when hint is not set. This causes ARIA issues and should be avoided by only referencing hint by id when it exists.
2. When the form controls are in error state and an error message is show, GOVUK components switch the `aria-describedby` value to reference the error message by ID, so assistive technology can inform the user on focus that there is an error. The above components don't this this.

## Corresponding PR

I raised a PR ([https://github.com/daniel-ac-martin/NotGovUK/pull/655](https://github.com/daniel-ac-martin/NotGovUK/pull/655)) that solves both problems.

## Screenshots

**Screenshot 1 - Error message is shown, but component doesn't reference it in `aria-describedby`**
![Screenshot 2023-01-13 at 16 48 21](https://user-images.githubusercontent.com/6372869/212374473-fa35ca04-f161-4150-b3d1-30234bfdf7b4.png)

**Screenshot 2 - non-existent hint is referenced by ID:**
![Screenshot 2023-01-13 at 16 47 35](https://user-images.githubusercontent.com/6372869/212374465-098c445c-a8c8-4891-bd6c-3e2de286732f.png)

**Comment by daniel-ac-martin** [comment]
Hi @robpataki.
Thanks for raising this. It looks like the first issue is limited to the components that are using FormGroup, but yes I agree.
Thanks also for taking the time to raise a PR, I'll respond there.

**Comment by robpataki** [comment]
Awesome, thanks @daniel-ac-martin . I'll leave you to it and will pick up when you're done with feeding back.

**Comment by daniel-ac-martin** [comment]
This has been fixed and will be in the next release (after v0.5.9).
