### ISSUE TITLE
New tag please 🙏 

### ISSUE THREAD

**Issue by robpataki** [daniel-ac-martin/NotGovUK#689]
Hello @daniel-ac-martin,

My team has been working on a non-public facing GOVUK project (one of many we've done in the past few years), where for the first time we decided to go with React/Next as opposed to the usual Nunkjucks-based GOVUK frontend. So far your library has been brilliant and in our experience a lot more intuitive, robust and closer to the original GOVUK origins than [govuk-react](https://github.com/govuk-react/govuk-react) 👏 

A few months in using your library we've found some issues that have been flagged on multiple accessibility audits we conducted - issues were raised around areas related to input hints, errors & conditionals - which we raised (https://github.com/daniel-ac-martin/NotGovUK/issues/656, https://github.com/daniel-ac-martin/NotGovUK/issues/654), and also offered solutions (https://github.com/daniel-ac-martin/NotGovUK/pull/655, https://github.com/daniel-ac-martin/NotGovUK/pull/658) in hope of not only solving the problem at source, but also making it easy for other dev teams to benefit via regular code merges and tag releases.

The only problem we're facing at the moment is there has not been a release or new tag created since October 2022, and despite my questions and comments on our issues and PRs, there has been no indication from you as to when a new tag will be released, so my team is now facing a challenging decision - we either wait indefinitely for a new !govuk tag to be released with the latest code updates (including [my accepted changes](https://github.com/daniel-ac-martin/NotGovUK/pull/655), which is very much needed for the digital service we're building at this point), or create a fork of !govuk and implement our code updates on our end in isolation, so our we can move on (benefiting us only).

We'd love to contribute and make other teams benefit from regular code updates and improvements, but without a new tag being released regularly, or any indication as of when one will come out it is very hard for us to plan and deliver at the same time.

Can you please let me know when you will release a new tag?

**Comment by daniel-ac-martin** [comment]
Hi @robpataki.
I'll try to make a new release soon. I just need to check whether there are any breaking changes so that I can work out the correct version number.

**Comment by daniel-ac-martin** [comment]
Looks like there is a potentially breaking change due to us updating from govuk-frontend v3 to v4.

So the next version should be v0.6.0...

@robpataki: How desperate are you for this release? Do you need it ASAP or can you wait a while longer?

**Comment by robpataki** [comment]
Hey @daniel-ac-martin 
"Looks like there is a potentially breaking change due to us updating from govuk-frontend v3 to v4." - that's somewhat expected, but as I remember the upgrade wasn't too bad (when using Nunjucks) - hopefully not too much effort to update on your end.

"So the next version should be v0.6.0" - Awesome, can't wait :)

"@robpataki: How desperate are you for this release? Do you need it ASAP or can you wait a while longer?
"Anyone working on a government project needs solutions - I wouldn't say we are desperate, but we are failing accessibility criteria and causing some confusion to certain users who rely on assistive technology. For my team (and I assume any other dev team working with `!govuk` in their project) it would be very handy to know what the release process is, and what the plan is around incremental releases and handling big bang breaking changes such as this one. 

At this point it seems like a big breaking change is getting in the way of smaller incremental changes (the accessibility issue fix and many of your NPM updates and other small improvements for example). I think the consuming teams would be better off if the release process was done in an incremental fashion.

Would it be possible to release a new tag with all the small changes (most importantly to my team at this point with ), and then focus on upgrading the major GOVUK Frontend version?

Having said that, I really appreciate how busy you must be, and how much work there is to do when you are maintaining a project such as this one, so thanks again for your hard work 🙏

**Comment by daniel-ac-martin** [comment]
https://github.com/daniel-ac-martin/NotGovUK/releases/tag/v0.6.0

**Comment by daniel-ac-martin** [comment]
@robpataki: I've released a new version. Let me know if you run into any problems.

The problem was that the major update to govuk-frontend had already gone in. I don't _think_ it should be a problem as we abstract most of it away.

I've been in the habit of doing small incremental changes until I hit a breaking change, and then trying to group up the breaking changes so they can be handled in one go. In the future, I'd like to handle this a bit better, probably by using a tool to keep track of the changes. (See: #291)

**Comment by robpataki** [comment]
Hey @daniel-ac-martin, excellent news, I'll check the new version this morning and will let you know. Thanks so much!
